[package]
name = "governance_backend"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.17.1"
ic-cdk-timers = "0.11.0" 
ic-cdk-macros = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ic-stable-structures = "0.6.7"
prost = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
